module.exports = [

    {
        "url" : "./data_schema.png",
        "title" : "data schema",
        "type" : "img",
        "description" : "This is my MVP project from the Codeop bootcamp. From the user's standpoint, apart from the About page, it was quite obscure; they just clicked on a \"magic\" (actually social policies, housing issues or climate change), then on a crystal ball, and after an 8 seconds animation were told they had sent an email after the fact. In the back end, I was scraping through puppeteer publicly available data from the Congreso de Diputados and Senado websites, which I stored in MySQL. I tied this with official party news site or the closest thing I could find, if that didn't exist. I was then sending this info (chosen magic, politician's name, and webpage) to the OpenAI API, asking it to parse the page and compose a message to figure out what was missing, or what they could do better. That message was then sent to the politician through nodemailer, from a email address made for the purpose of this project.",
        "link" : "https://github.com/luluconcha/mvp/blob/main/README.md",
        "tag" : "crystalball",
        "first" : 1,
    },
    {
        "url" : "https://www.loom.com/embed/5bd31f44d95e4c1f9c470a1ed8700f34?sid=6f58399b-f597-4789-9a91-8beb0d1d00a5",
        "title" : "Crystalball demo",
        "type" : "video",
        "link" : 0,
        "description" : "What this project looked like on the front end --animation handmade by yours truly",
        "tag" : "crystalball",
        "first" : 0,
    },
    {
        "url" : "./estherdelbrio.png",
        "title" : "\"Sent from my iPhone\"",
        "type" : "img",
        "link" : 0,
        "description" : "Out of maybe a hundred emails sent, only one Senator answered!",
        "tag" : "crystalball",
        "first" : 0,
    },
    {
        "url" : "./storymapping_userflow.png",
        "title" : "Storymap UX flow",
        "link" : "https://github.com/luluconcha/storymapping",
        "type" : "img",
        "description" : "Hopefully pretty self-explanatory, this one",
        "tag" : "storymap",
        "first" : 0,
    },
    {
        "url" : "./cotton_candy_land.png",
        "title" : "Cotton Candy Land",
        "type" : "img",
        "link" : "https://github.com/luluconcha/mvp_extended/blob/master/routes/storypoints.js",
        "description" : "First iteration of the final Storymap project; the bootcamp's second project was a feature extension on someone else's project. My colleague's project was a SPA to create character sheets; I decided to extend this by creating a tree-like Sequelize database where users could contribute to a collective choose-your-own-adventure kind of story. Given the 4 days deadline for this project, I did not get around to tying the characters to the storypoints --but for the last 3-week group project, we decided to create a full-fleshed, actually playable version of this.",
        "tag" : "storymap",
        "first" : 0,
    },
    {
        "url" : "./storymapping_database.png",
        "title" : "Storymap database",
        "type" : "img",
        "link" : 0,
        "description" : "Storymap project database demonstrating the links between a user's characters, abilities, and items, and the visited or created Storypoints and the challenges they may contain.",
        "tag" : "storymap",
        "first" : 1,
    },
    {
        "url" : "https://www.loom.com/embed/effeb1d975614df986e746f76bd85f4f?sid=6912a135-126c-45cb-a02c-fae08aca5b6f",
        "title" : "Storymap demo",
        "link" : "https://github.com/luluconcha/storymapping",
        "type" : "video",
        "description" : "Front end demo of the Storymap project",
        "tag" : "storymap",
        "first" : 0,
    },
    {
        "url" : "https://www.youtube.com/embed/TvmU7JxWKT8?si=17baD1aa4Trhuav0",
        "title" : "Kingdom Vallcarca",
        "link" : 0,
        "type" : "video",
        "description" : "Short movie about a small part of the Vallcarca neighborhood in Barcelona, selected for the Clic Festival 2021. I am passionate about community, small-scale resistance, and sustainable ways of life. I would love to be able to make a full-length feature on this at some point.",
        "tag" : "random non-tech projects",
        "first" : 0,
    },
    {
        "url" : "./santa_jordina.jpg",
        "title" : "Graphic projects",
        "link" : 0,
        "type" : "img",
        "description" : "I am also interested in graphic design, and using this for social causes. This poster was made for a community library I volunteer at.",
        "tag" : "random non-tech projects",
        "first" : 1,
    },
    {
        "url" : "./feliz_cumple2021.mp4",
        "title" : "\"Feliz cumpleaños\"",
        "link" : 0,
        "type" : "video",
        "description" : "Because I also love making stop-motion, I decided to include this labor of love made for a friend's birthday. ",
        "tag" : "random non-tech projects",
        "first" : 0,
    },

]